### ISSUE TITLE
Error when clicked...

### ISSUE THREAD

**Issue by gabriel-q7** [Elijah-trillionz/devRoadMap#2]
I clone the repo in my pc, in the index page when I click in the "I'd like to create..." occurs a error "Error fetching data. Please try again". I'm using Brave web browser.
![error](https://user-images.githubusercontent.com/62434450/196457565-98d89ae5-cae9-4131-8e77-e890df965a58.PNG)

**Comment by Elijah-trillionz** [comment]
Hello @gabriel-q7.
Thanks for pointing this out, I'm going to try and reproduce it and see if I encounter the same issue.

**Comment by Elijah-trillionz** [comment]
The error is caused by the fact that you're not using a local server that serves both the resources and the `index.html` file. If you open it using VSCode live server extension, everything will work fine.
But this issue would trigger a feature for it to run on Vite, so everyone contributing can easily get along.

So I'm going to close this issue and create a new issue with a feature tag. But if you are interested in adding Vite yourself (because you discovered it and you should take the credit), please let me know.

**Comment by gabriel-q7** [comment]
Got it. I try it with live server, it worked. I'm not used to Vite, but this topic could be in a further discuss.
